export { default as Header } from './Header/Header'
export { default as Players } from './Players/Players'
export { default as Rules } from './Rules/Rules'
export { default as Game } from './Game/Game'
export { default as ResetBtn } from './ResetBtn/ResetBtn'